server:
  port:  8094
  
spring:
  config:
    import: optional:configserver:http://localhost:8095
   #import: optional:configserver:http://localhost:8095
  application:
    name: API-GATEWAY 
    
  cloud:
    gateway:
      routes:
      - id: USER_SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
          - Path=/hotels/**,/staffs/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
          - Path=/ratings/**
    
#    okta configuration for api gateway
#okta:
#  oauth2:
#    issuer: https://.okta.com/oauth2/default
#    audience: api://default
#    client-id: 
#    client-secret: 
#    scopes: openid, profile, email, offline_access


    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
